string = 'python in easy steps'

print('\nCapitalized:\t\t', string.capitalize())
print('\nTitled:\t\t\t\t', string.title())
print('\nUppercase:\t\t\t', string.upper())
print('\nLowercase:\t\t\t', string.lower())
print('\nSwapCase:\t\t\t', string.swapcase())
print('\nJoin:\t\t\t\t', string.join('+**+'))
print('\nLeft Strip:\t\t\t', string.lstrip('p'))
print('\nRight Strip:\t\t', string.rstrip('s'))
print('\nStrip:\t\t\t\t', string.strip('yps'))
print('\nReplace:\t\t\t', string.replace('p', '^'))
print('\nPad Left:\t\t\t', string.ljust(25, 'p'))
print('\nPad Right:\t\t\t', string.rjust(25, 'i'))
print('\nCenter:\t\t\t\t', string.center(30, '$'))
print('\nCount:\t\t\t\t', string.count('p'))
print('\nFind:\t\t\t\t', string.find('y'))
print('\nStarts With:\t\t', string.startswith('py'))
print('\nEnds With:\t\t\t', string.endswith('sy'))
print('\nIs Alpha:\t\t\t', string.isalpha())
print('\nIs Numeric:\t\t\t', string.isnumeric())
print('\nIs Alpha Numeric:\t', string.isalnum())
print('\nIs Lower:\t\t\t', string.islower())
print('\nIs Upper:\t\t\t', string.isupper())
print('\nIs Title:\t\t\t', string.istitle())
print('\nIs Space:\t\t\t', string.isspace())
print('\nIs Digit:\t\t\t', string.isdigit())
print('\nIs Decimal:\t\t\t', string.isdecimal())
