a = input('\nEnter a number: ')
b = input('Now enter another number: ')

total = a + b
print('\n01-Data Type sum:', total, type(total))
total = int(a) + int(b)
print('02-Data Type sum:', total, type(total))
total = float(total)
print('03-Data Type sum:', total, type(total))
total = chr(int(total))
print('04-Data Type sum:', total, type(total))
total = ord(total)
print('05-Data Type sum:', total, type(total))
hextotal = hex(total)
print('06-Data Type sum:', hextotal, type(hextotal))
octtotal = oct(total)
print('07-Data Type sum:', octtotal, type(octtotal))
